FROM alpine:3.14

RUN apk update && apk add --no-cache mariadb mariadb-client

COPY conf/my.cnf /etc/mysql/my.cnf
COPY tools/mariadb_start.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/mariadb_start.sh

EXPOSE 3306

CMD ["/usr/local/bin/mariadb_start.sh"]